### ISSUE TITLE
Uncaught ReferenceError: videojs is not defined

### ISSUE THREAD

**Issue by blumonn** [jfujita/videojs-http-source-selector#1]
Hi,

after building the plugin and importing in my project, trying to run the project gives me the following error : 

    videojs-http-source-selector.es.js:57 Uncaught ReferenceError: videojs is not defined
    at eval (videojs-http-source-selector.es.js:57)
    at Module../node_modules/videojs-http-source-selector/dist/videojs-http-source-selector.es.js (bundle.js:704)
    at __webpack_require__ (bundle.js:20)
    at eval (index.js:6)
    at Module../index.js (bundle.js:97)
    at __webpack_require__ (bundle.js:20)
    at bundle.js:84
    at bundle.js:87

after some digging, seems like this is a problem related to [this generator-videojs-plugin issue](https://github.com/videojs/generator-videojs-plugin/issues/193), which happened because of something funky with rollup. 

How to resolve this? Any help is much appreciated.

**Comment by bricesanchez** [comment]
Hi @blumonn, I've the same error, did you find a solution?

**Comment by bricesanchez** [comment]
I think the dist is broken in ES : 
https://github.com/pivotshare/videojs-http-source-selector/blob/master/dist/videojs-http-source-selector.es.js#L1

Should it be `videojs` instead of `videojs$1` ?

**Comment by blumonn** [comment]
@bricesanchez I imported videojs in the components and built the plugin again. that seemed to work for me.

**Comment by MTonomy-Nchinda-Nchinda** [comment]
Until this is fixed via PR, I've been importing this library as
```
import videojs from 'video.js';
window.videojs = videojs;
require('videojs-http-source-selector');
```
