### ISSUE TITLE
menu item selected style doesnt work

### ISSUE THREAD

**Issue by Yahasana** [jfujita/videojs-http-source-selector#7]

**Comment by msjh80311** [comment]
+1
When clicking on one of the quality menu list item, the source successfully changed.
However, **the selected list item doesn't show any style** (ex, with background color or different text color from the un-selected ones) to recognize which is selected.

**Comment by MichSimi** [comment]
+1
not add .vjs-selected class to the .vjs-menu-item

**Comment by leonklingele** [comment]
This probably is because the item is not marked `selectable`: https://github.com/videojs/video.js/blob/4b325ea8f8188a5db76489243f7469ba8f7995ba/src/js/menu/menu-item.js#L111
